### ISSUE TITLE
Add a new function that renew automatically the free domain on no-ip.com periodically

### ISSUE THREAD

**Issue by bphd** [diversen/noiphp#1]

**Comment by diversen** [comment]
You could setup a cron job?

(Every 5 minut)

*/5 * * * * php /users/someuser/noiphp/run.php

**Comment by bphd** [comment]
This will update the IP, not renew the domain

**Comment by diversen** [comment]
I think it is outside the scope of this project. I don't have the time to implement it. But there is a project that seems to handle this: https://github.com/loblab/noip-renew
